SAFE_WHITELIST = {
    "google.com": [
        "www.google.com",
        "accounts.google.com",
        "mail.google.com",
        "drive.google.com",
        "photos.google.com",
        "docs.google.com",
        "maps.google.com",
        "play.google.com",
        "news.google.com",
        "translate.google.com",
        "meet.google.com",
        "chat.google.com",
        "calendar.google.com",
        "keep.google.com",
        "wallet.google.com",
        "shopping.google.com",
        "books.google.com",
    ],
    "youtube.com": [
        "www.youtube.com",
        "m.youtube.com",
        "music.youtube.com",
        "studio.youtube.com",
    ],
    "facebook.com": [
        "www.facebook.com",
        "m.facebook.com",
        "business.facebook.com",
    ],
    "twitter.com": [
        "www.twitter.com",
        "mobile.twitter.com",
        "x.com",
    ],
    "linkedin.com": [
        "www.linkedin.com",
        "linkedin.com",
    ],
    "microsoft.com": [
        "www.microsoft.com",
        "login.microsoftonline.com",
        "office.com",
        "outlook.com",
        "teams.microsoft.com",
    ],
    "apple.com": [
        "www.apple.com",
        "id.apple.com",
        "support.apple.com",
        "developer.apple.com",
    ],
    "amazon.com": [
        "www.amazon.com",
        "smile.amazon.com",
        "sellercentral.amazon.com",
    ],
    "github.com": [
        "github.com",
        "www.github.com",
    ],
    "gitlab.com": [
        "gitlab.com",
        "www.gitlab.com",
    ],
    "stackoverflow.com": [
        "stackoverflow.com",
        "www.stackoverflow.com",
    ],
    "reddit.com": [
        "www.reddit.com",
        "old.reddit.com",
        "reddit.com",
    ],
    "wikipedia.org": [
        "www.wikipedia.org",
        "en.wikipedia.org",
        "de.wikipedia.org",
    ],
    "netflix.com": ["www.netflix.com"],
    "paypal.com": ["www.paypal.com"],
    "spotify.com": ["www.spotify.com"],
    "slack.com": ["slack.com", "www.slack.com"],
    "dropbox.com": ["www.dropbox.com"],
    "zoom.us": ["zoom.us", "www.zoom.us"],
    "tiktok.com": ["www.tiktok.com"],
    "snapchat.com": ["www.snapchat.com"],
    "whatsapp.com": ["www.whatsapp.com"],
    "discord.com": ["discord.com", "www.discord.com"],
    "telegram.org": ["telegram.org", "web.telegram.org"],
    "vimeo.com": ["vimeo.com"],
    "twitch.tv": ["twitch.tv"],
    "bilibili.com": ["bilibili.com"],
    "dailymotion.com": ["dailymotion.com"],
    "vkontakte.ru": ["vk.com"],
    "baidu.com": ["baidu.com"],
    "yandex.ru": ["yandex.ru"],
    "yahoo.com": ["yahoo.com"],
    "alibaba.com": ["alibaba.com"],
    "ebay.com": ["ebay.com"],
    "etsy.com": ["etsy.com"],
    "airbnb.com": ["airbnb.com"],
    "booking.com": ["booking.com"],
    "expedia.com": ["expedia.com"],
    "tripadvisor.com": ["tripadvisor.com"],
    "skyscanner.com": ["skyscanner.com"],
    "kayak.com": ["kayak.com"],
    "weather.com": ["weather.com"],
    "bbc.com": ["bbc.com"],
    "cnn.com": ["cnn.com"],
    "nytimes.com": ["nytimes.com"],
    "reuters.com": ["reuters.com"],
    "forbes.com": ["forbes.com"],
    "bloomberg.com": ["bloomberg.com"],
    "cnbc.com": ["cnbc.com"],
    "businessinsider.com": ["businessinsider.com"],
    "theguardian.com": ["theguardian.com"],
    "theverge.com": ["theverge.com"],
    "techcrunch.com": ["techcrunch.com"],
    "wired.com": ["wired.com"],
    "engadget.com": ["engadget.com"],
    "mashable.com": ["mashable.com"],
    "lifehacker.com": ["lifehacker.com"],
    "howtogeek.com": ["howtogeek.com"],
    "makeuseof.com": ["makeuseof.com"],
    "tomshardware.com": ["tomshardware.com"],
    "cnet.com": ["cnet.com"],
    "pcmag.com": ["pcmag.com"],
    "zdnet.com": ["zdnet.com"],
    "arstechnica.com": ["arstechnica.com"],
    "gizmodo.com": ["gizmodo.com"],
    "slashdot.org": ["slashdot.org"],
    "news.ycombinator.com": ["news.ycombinator.com"],
    "producthunt.com": ["producthunt.com"],
    "betalist.com": ["betalist.com"],
    "indiehackers.com": ["indiehackers.com"],
    "github.io": ["github.io"],
    "gitlab.io": ["gitlab.io"],
    "bitbucket.org": ["bitbucket.org"],
    "sourceforge.net": ["sourceforge.net"],
    "npmjs.com": ["npmjs.com"],
    "yarnpkg.com": ["yarnpkg.com"],
    "docker.com": ["docker.com"],
    "kubernetes.io": ["kubernetes.io"],
    "ansible.com": ["ansible.com"],
    "terraform.io": ["terraform.io"],
    "hashicorp.com": ["hashicorp.com"],
    "chef.io": ["chef.io"],
    "puppet.com": ["puppet.com"],
    "saltstack.com": ["saltstack.com"],
    "jenkins.io": ["jenkins.io"],
    "circleci.com": ["circleci.com"],
    "travis-ci.org": ["travis-ci.org"],
    "appveyor.com": ["appveyor.com"],
    "codeship.com": ["codeship.com"],
    "bitrise.io": ["bitrise.io"],
    "fastlane.tools": ["fastlane.tools"],
    "fastapi.tiangolo.com": ["fastapi.tiangolo.com"],
    "flask.palletsprojects.com": ["flask.palletsprojects.com"],
    "djangoproject.com": ["djangoproject.com"],
    "railsware.com": ["railsware.com"],
    "laravel.com": ["laravel.com"],
    "symfony.com": ["symfony.com"],
    "angular.io": ["angular.io"],
    "reactjs.org": ["reactjs.org"],
    "vuejs.org": ["vuejs.org"],
    "svelte.dev": ["svelte.dev"],
    "nextjs.org": ["nextjs.org"],
    "nuxtjs.org": ["nuxtjs.org"],
    "gatsbyjs.com": ["gatsbyjs.com"],
    "netlify.com": ["netlify.com"],
    "vercel.com": ["vercel.com"],
    "heroku.com": ["heroku.com"],
    "render.com": ["render.com"],
    "fly.io": ["fly.io"],
    "railway.app": ["railway.app"],
    "replit.com": ["replit.com"],
    "codesandbox.io": ["codesandbox.io"],
    "stackblitz.com": ["stackblitz.com"],
    "glitch.com": ["glitch.com"],
    "codepen.io": ["codepen.io"],
    "jsfiddle.net": ["jsfiddle.net"],
    "jsbin.com": ["jsbin.com"],
    "plnkr.co": ["plnkr.co"],
    "codeply.com": ["codeply.com"],
    "jsdo.it": ["jsdo.it"],
    "jsitor.com": ["jsitor.com"],
    "codewars.com": ["codewars.com"],
    "exercism.io": ["exercism.io"],
    "freecodecamp.org": ["freecodecamp.org"],
    "udemy.com": ["udemy.com"],
    "coursera.org": ["coursera.org"],
    "edx.org": ["edx.org"],
    "khanacademy.org": ["khanacademy.org"],
}
